trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UseNode@2
    inputs:
      versionSpec: '14.x'

  - script: |
      npm install
      npm test
    displayName: 'Install dependencies and run tests'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'dist'
      artifactName: 'drop'

  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'YourServiceConnection'
      appName: 'YourTestEnvironmentApp'
      package: '$(Pipeline.Workspace)/drop'
